[tool.poetry]
name = "genome-circos"
version = "0.0.2"
description = "Genome circos python package."
authors = ["Wenlin Xu <wenlinxu.njfu@outlook.com>"]
homepage = "https://github.com/wenlinXu-njfu/GenomeCircos"
license = "MIT"
readme = "README.md"
packages = [{include = "genome_circos"}]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^2.0.3"
matplotlib = "^3.7.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"